### ISSUE TITLE
LoadError: Cannot locate artifact 'blpapi'

### ISSUE THREAD

**Issue by banachtech** [felipenoris/BLPData.jl#19]
Seems like an Apple silicon specific issue? On M1 Max Studio:

`Precompiling project...
  ✗ BLPData
  1 dependency successfully precompiled in 1 seconds. 289 already precompiled.
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package

julia> using BLPData
[ Info: Precompiling BLPData [eb622722-88ce-45f2-a8b9-c2f73a5cb263]
ERROR: LoadError: Cannot locate artifact 'blpapi' for aarch64-apple-darwin-libgfortran5-cxx11-julia_version+1.8.2 in '/Users/xxxx/.julia/packages/BLPData/huief/Artifacts.toml'
`

**Comment by felipenoris** [comment]
Yes, this is a M1 issue.

I don't know if the macos artifact is compatible with M1. Given that Bloomberg provides the compiled binary (see <https://www.bloomberg.com/professional/support/api-library/>), my guess is that it was not compiled for aarch64.

One thing you can try is to add this to your `Artifacts.toml` file and retry. 

```toml
[[blpapi]]
arch = "aarch64"
git-tree-sha1 = "2efdd93e172b25ccb55877c2006e1dbe8790b5a4"
os = "macos"

    [[blpapi.download]]
    sha256 = "5a2bbd14da0e46f6aed8c02da5c4917baa1fffa958ebb0d2c02e22ddab4fa222"
    url = "https://github.com/felipenoris/BLPData.jl/releases/download/blpapi-3.12.3.1/blpapi_cpp_3.14.3.1-macos-x64.tar.gz"
```
